---
title: "Sampling the Imaginary"
author: "Yashas Nadig"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
Pr_Positive_Vampire <- 0.95
Pr_Positive_Mortal <- 0.01
Pr_Vampire <- 0.001
Pr_Positive <- Pr_Positive_Vampire * Pr_Vampire +
Pr_Positive_Mortal * ( 1 - Pr_Vampire )
( Pr_Vampire_Positive <- Pr_Positive_Vampire*Pr_Vampire / Pr_Positive )
```

```{r}
p_grid <- seq( from=0 , to=1 , length.out=1000 )
prob_p <- rep( 1 , 1000 )
prob_data <- dbinom( 6 , size=9 , prob=p_grid )
posterior <- prob_data * prob_p
posterior <- posterior / sum(posterior)
```

```{r}
samples <- sample( p_grid , prob=posterior , size=1e4 , replace=TRUE )
```

```{r}
plot( samples )
```

```{r}
library(rethinking)
dens( samples )
```

```{r}
# add up posterior probability where p < 0.5
sum( posterior[ p_grid < 0.5 ])
```

```{r}
sum( samples < 0.5 ) / 1e4
```

```{r}
sum( samples > 0.5 & samples < 0.75 ) / 1e4
```

```{r}
quantile( samples , 0.8 )
```

```{r}
quantile( samples , c( 0.1 , 0.9 ) )
```

```{r}
p_grid <- seq( from=0 , to=1 , length.out=1000 )
prior <- rep(1,1000)
likelihood <- dbinom( 3 , size=3 , prob=p_grid )
posterior <- likelihood * prior
posterior <- posterior / sum(posterior)
samples <- sample( p_grid , size=1e4 , replace=TRUE , prob=posterior )
```

```{r}
PI( samples , prob=0.5 )
```

```{r}
HPDI( samples , prob=0.5 )
```

```{r}
p_grid[ which.max(posterior) ]
```

```{r}
chainmode( samples , adj=0.01 )
```

```{r}
mean( samples )
median( samples )
```

```{r}
sum( posterior*abs( 0.5 - p_grid ) )
```

```{r}
loss <- sapply( p_grid , function(d) sum( posterior*abs( d - p_grid ) ) )
```

```{r}
p_grid[which.min(loss)]
```

```{r}
dbinom( 0:2 , size=2 , prob=0.7 )
```














